
    create table categoria (
       id integer generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table cidade (
       id integer generated by default as identity,
        nome varchar(255),
        estado_id integer,
        primary key (id)
    );

    create table cliente (
       id integer generated by default as identity,
        cpf_ou_cnpj varchar(255),
        email varchar(255),
        nome varchar(255),
        tipo integer,
        primary key (id)
    );

    create table cliente_pedidos (
       cliente_id integer not null,
        pedidos_id integer not null
    );

    create table endereco (
       id integer generated by default as identity,
        bairro varchar(255),
        cep varchar(255),
        complemento varchar(255),
        logradouro varchar(255),
        numero varchar(255),
        cidade_id integer,
        cliente_id integer,
        primary key (id)
    );

    create table estado (
       id integer generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table estado_cidades (
       estado_id integer not null,
        cidades_id integer not null
    );

    create table item_pedido (
       desconto double,
        preco double,
        quantidade integer,
        pedido_id integer not null,
        produto_id integer not null,
        primary key (pedido_id, produto_id)
    );

    create table pagamento (
       pedido_id integer not null,
        estado integer,
        primary key (pedido_id)
    );

    create table pagamento_com_boleto (
       data_pagamento timestamp,
        data_vencimento timestamp,
        pedido_id integer not null,
        primary key (pedido_id)
    );

    create table pagamento_com_cartão (
       numero_de_parcelas integer,
        pedido_id integer not null,
        primary key (pedido_id)
    );

    create table pedido (
       id integer generated by default as identity,
        instante timestamp,
        cliente_id integer,
        endereco_de_entrega_id integer,
        primary key (id)
    );

    create table produto (
       id integer generated by default as identity,
        nome varchar(255),
        preco double,
        primary key (id)
    );

    create table produto_categaoria (
       produto_id integer not null,
        categoria_id integer not null
    );

    create table telefone (
       cliente_id integer not null,
        telefones varchar(255)
    );

    alter table cliente_pedidos 
       add constraint UK_5ghbygu6ffc8sd7dnlxud5mox unique (pedidos_id);

    alter table estado_cidades 
       add constraint UK_gijjfjo51s66b3d93dqfknv42 unique (cidades_id);

    alter table cidade 
       add constraint FKkworrwk40xj58kevvh3evi500 
       foreign key (estado_id) 
       references estado;

    alter table cliente_pedidos 
       add constraint FKprs510oqt9komm63bt9hqn6g 
       foreign key (pedidos_id) 
       references pedido;

    alter table cliente_pedidos 
       add constraint FK3fiiwebwnib50do1jwwdtp2gv 
       foreign key (cliente_id) 
       references cliente;

    alter table endereco 
       add constraint FK8b1kcb3wucapb8dejshyn5fsx 
       foreign key (cidade_id) 
       references cidade;

    alter table endereco 
       add constraint FK8s7ivtl4foyhrfam9xqom73n9 
       foreign key (cliente_id) 
       references cliente;

    alter table estado_cidades 
       add constraint FKdsru97k6bsynqe9wc4teuap59 
       foreign key (cidades_id) 
       references cidade;

    alter table estado_cidades 
       add constraint FKb2ry2y5u2495mmteeveyt6ifd 
       foreign key (estado_id) 
       references estado;

    alter table item_pedido 
       add constraint FK60ym08cfoysa17wrn1swyiuda 
       foreign key (pedido_id) 
       references pedido;

    alter table item_pedido 
       add constraint FKtk55mn6d6bvl5h0no5uagi3sf 
       foreign key (produto_id) 
       references produto;

    alter table pagamento 
       add constraint FKthad9tkw4188hb3qo1lm5ueb0 
       foreign key (pedido_id) 
       references pedido;

    alter table pagamento_com_boleto 
       add constraint FKcr74vrxf8nfph0knq2bho8doo 
       foreign key (pedido_id) 
       references pagamento;

    alter table pagamento_com_cartão 
       add constraint FKtq9q8c39holyyu8tlkm2m6k2u 
       foreign key (pedido_id) 
       references pagamento;

    alter table pedido 
       add constraint FK30s8j2ktpay6of18lbyqn3632 
       foreign key (cliente_id) 
       references cliente;

    alter table pedido 
       add constraint FK1fihyy2fnocpuwc74674qmfkv 
       foreign key (endereco_de_entrega_id) 
       references endereco;

    alter table produto_categaoria 
       add constraint FK8x787ynuy0pwb7rs3oxop8d5o 
       foreign key (categoria_id) 
       references categoria;

    alter table produto_categaoria 
       add constraint FKcw2rbwom5a8yry1d3wth6ev8y 
       foreign key (produto_id) 
       references produto;

    alter table telefone 
       add constraint FK8aafha0njkoyoe3kvrwsy3g8u 
       foreign key (cliente_id) 
       references cliente;

    create table categoria (
       id integer generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table cidade (
       id integer generated by default as identity,
        nome varchar(255),
        estado_id integer,
        primary key (id)
    );

    create table cliente (
       id integer generated by default as identity,
        cpf_ou_cnpj varchar(255),
        email varchar(255),
        nome varchar(255),
        tipo integer,
        primary key (id)
    );

    create table cliente_pedidos (
       cliente_id integer not null,
        pedidos_id integer not null
    );

    create table endereco (
       id integer generated by default as identity,
        bairro varchar(255),
        cep varchar(255),
        complemento varchar(255),
        logradouro varchar(255),
        numero varchar(255),
        cidade_id integer,
        cliente_id integer,
        primary key (id)
    );

    create table estado (
       id integer generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table estado_cidades (
       estado_id integer not null,
        cidades_id integer not null
    );

    create table item_pedido (
       desconto double,
        preco double,
        quantidade integer,
        pedido_id integer not null,
        produto_id integer not null,
        primary key (pedido_id, produto_id)
    );

    create table pagamento (
       pedido_id integer not null,
        estado integer,
        primary key (pedido_id)
    );

    create table pagamento_com_boleto (
       data_pagamento timestamp,
        data_vencimento timestamp,
        pedido_id integer not null,
        primary key (pedido_id)
    );

    create table pagamento_com_cartão (
       numero_de_parcelas integer,
        pedido_id integer not null,
        primary key (pedido_id)
    );

    create table pedido (
       id integer generated by default as identity,
        instante timestamp,
        cliente_id integer,
        endereco_de_entrega_id integer,
        primary key (id)
    );

    create table produto (
       id integer generated by default as identity,
        nome varchar(255),
        preco double,
        primary key (id)
    );

    create table produto_categaoria (
       produto_id integer not null,
        categoria_id integer not null
    );

    create table telefone (
       cliente_id integer not null,
        telefones varchar(255)
    );

    alter table cliente_pedidos 
       add constraint UK_5ghbygu6ffc8sd7dnlxud5mox unique (pedidos_id);

    alter table estado_cidades 
       add constraint UK_gijjfjo51s66b3d93dqfknv42 unique (cidades_id);

    alter table cidade 
       add constraint FKkworrwk40xj58kevvh3evi500 
       foreign key (estado_id) 
       references estado;

    alter table cliente_pedidos 
       add constraint FKprs510oqt9komm63bt9hqn6g 
       foreign key (pedidos_id) 
       references pedido;

    alter table cliente_pedidos 
       add constraint FK3fiiwebwnib50do1jwwdtp2gv 
       foreign key (cliente_id) 
       references cliente;

    alter table endereco 
       add constraint FK8b1kcb3wucapb8dejshyn5fsx 
       foreign key (cidade_id) 
       references cidade;

    alter table endereco 
       add constraint FK8s7ivtl4foyhrfam9xqom73n9 
       foreign key (cliente_id) 
       references cliente;

    alter table estado_cidades 
       add constraint FKdsru97k6bsynqe9wc4teuap59 
       foreign key (cidades_id) 
       references cidade;

    alter table estado_cidades 
       add constraint FKb2ry2y5u2495mmteeveyt6ifd 
       foreign key (estado_id) 
       references estado;

    alter table item_pedido 
       add constraint FK60ym08cfoysa17wrn1swyiuda 
       foreign key (pedido_id) 
       references pedido;

    alter table item_pedido 
       add constraint FKtk55mn6d6bvl5h0no5uagi3sf 
       foreign key (produto_id) 
       references produto;

    alter table pagamento 
       add constraint FKthad9tkw4188hb3qo1lm5ueb0 
       foreign key (pedido_id) 
       references pedido;

    alter table pagamento_com_boleto 
       add constraint FKcr74vrxf8nfph0knq2bho8doo 
       foreign key (pedido_id) 
       references pagamento;

    alter table pagamento_com_cartão 
       add constraint FKtq9q8c39holyyu8tlkm2m6k2u 
       foreign key (pedido_id) 
       references pagamento;

    alter table pedido 
       add constraint FK30s8j2ktpay6of18lbyqn3632 
       foreign key (cliente_id) 
       references cliente;

    alter table pedido 
       add constraint FK1fihyy2fnocpuwc74674qmfkv 
       foreign key (endereco_de_entrega_id) 
       references endereco;

    alter table produto_categaoria 
       add constraint FK8x787ynuy0pwb7rs3oxop8d5o 
       foreign key (categoria_id) 
       references categoria;

    alter table produto_categaoria 
       add constraint FKcw2rbwom5a8yry1d3wth6ev8y 
       foreign key (produto_id) 
       references produto;

    alter table telefone 
       add constraint FK8aafha0njkoyoe3kvrwsy3g8u 
       foreign key (cliente_id) 
       references cliente;

    create table categoria (
       id integer generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table cidade (
       id integer generated by default as identity,
        nome varchar(255),
        estado_id integer,
        primary key (id)
    );

    create table cliente (
       id integer generated by default as identity,
        cpf_ou_cnpj varchar(255),
        email varchar(255),
        nome varchar(255),
        tipo integer,
        primary key (id)
    );

    create table cliente_pedidos (
       cliente_id integer not null,
        pedidos_id integer not null
    );

    create table endereco (
       id integer generated by default as identity,
        bairro varchar(255),
        cep varchar(255),
        complemento varchar(255),
        logradouro varchar(255),
        numero varchar(255),
        cidade_id integer,
        cliente_id integer,
        primary key (id)
    );

    create table estado (
       id integer generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table estado_cidades (
       estado_id integer not null,
        cidades_id integer not null
    );

    create table item_pedido (
       desconto double,
        preco double,
        quantidade integer,
        pedido_id integer not null,
        produto_id integer not null,
        primary key (pedido_id, produto_id)
    );

    create table pagamento (
       pedido_id integer not null,
        estado integer,
        primary key (pedido_id)
    );

    create table pagamento_com_boleto (
       data_pagamento timestamp,
        data_vencimento timestamp,
        pedido_id integer not null,
        primary key (pedido_id)
    );

    create table pagamento_com_cartao (
       numero_de_parcelas integer,
        pedido_id integer not null,
        primary key (pedido_id)
    );

    create table pedido (
       id integer generated by default as identity,
        instante timestamp,
        cliente_id integer,
        endereco_de_entrega_id integer,
        primary key (id)
    );

    create table produto (
       id integer generated by default as identity,
        nome varchar(255),
        preco double,
        primary key (id)
    );

    create table produto_categaoria (
       produto_id integer not null,
        categoria_id integer not null
    );

    create table telefone (
       cliente_id integer not null,
        telefones varchar(255)
    );

    alter table cliente_pedidos 
       add constraint UK_5ghbygu6ffc8sd7dnlxud5mox unique (pedidos_id);

    alter table estado_cidades 
       add constraint UK_gijjfjo51s66b3d93dqfknv42 unique (cidades_id);

    alter table cidade 
       add constraint FKkworrwk40xj58kevvh3evi500 
       foreign key (estado_id) 
       references estado;

    alter table cliente_pedidos 
       add constraint FKprs510oqt9komm63bt9hqn6g 
       foreign key (pedidos_id) 
       references pedido;

    alter table cliente_pedidos 
       add constraint FK3fiiwebwnib50do1jwwdtp2gv 
       foreign key (cliente_id) 
       references cliente;

    alter table endereco 
       add constraint FK8b1kcb3wucapb8dejshyn5fsx 
       foreign key (cidade_id) 
       references cidade;

    alter table endereco 
       add constraint FK8s7ivtl4foyhrfam9xqom73n9 
       foreign key (cliente_id) 
       references cliente;

    alter table estado_cidades 
       add constraint FKdsru97k6bsynqe9wc4teuap59 
       foreign key (cidades_id) 
       references cidade;

    alter table estado_cidades 
       add constraint FKb2ry2y5u2495mmteeveyt6ifd 
       foreign key (estado_id) 
       references estado;

    alter table item_pedido 
       add constraint FK60ym08cfoysa17wrn1swyiuda 
       foreign key (pedido_id) 
       references pedido;

    alter table item_pedido 
       add constraint FKtk55mn6d6bvl5h0no5uagi3sf 
       foreign key (produto_id) 
       references produto;

    alter table pagamento 
       add constraint FKthad9tkw4188hb3qo1lm5ueb0 
       foreign key (pedido_id) 
       references pedido;

    alter table pagamento_com_boleto 
       add constraint FKcr74vrxf8nfph0knq2bho8doo 
       foreign key (pedido_id) 
       references pagamento;

    alter table pagamento_com_cartao 
       add constraint FKta3cdnuuxclwfh52t4qi432ow 
       foreign key (pedido_id) 
       references pagamento;

    alter table pedido 
       add constraint FK30s8j2ktpay6of18lbyqn3632 
       foreign key (cliente_id) 
       references cliente;

    alter table pedido 
       add constraint FK1fihyy2fnocpuwc74674qmfkv 
       foreign key (endereco_de_entrega_id) 
       references endereco;

    alter table produto_categaoria 
       add constraint FK8x787ynuy0pwb7rs3oxop8d5o 
       foreign key (categoria_id) 
       references categoria;

    alter table produto_categaoria 
       add constraint FKcw2rbwom5a8yry1d3wth6ev8y 
       foreign key (produto_id) 
       references produto;

    alter table telefone 
       add constraint FK8aafha0njkoyoe3kvrwsy3g8u 
       foreign key (cliente_id) 
       references cliente;

    create table categoria (
       id integer generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table cidade (
       id integer generated by default as identity,
        nome varchar(255),
        estado_id integer,
        primary key (id)
    );

    create table cliente (
       id integer generated by default as identity,
        cpf_ou_cnpj varchar(255),
        email varchar(255),
        nome varchar(255),
        tipo integer,
        primary key (id)
    );

    create table cliente_pedidos (
       cliente_id integer not null,
        pedidos_id integer not null
    );

    create table endereco (
       id integer generated by default as identity,
        bairro varchar(255),
        cep varchar(255),
        complemento varchar(255),
        logradouro varchar(255),
        numero varchar(255),
        cidade_id integer,
        cliente_id integer,
        primary key (id)
    );

    create table estado (
       id integer generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table estado_cidades (
       estado_id integer not null,
        cidades_id integer not null
    );

    create table item_pedido (
       desconto double,
        preco double,
        quantidade integer,
        pedido_id integer not null,
        produto_id integer not null,
        primary key (pedido_id, produto_id)
    );

    create table pagamento (
       pedido_id integer not null,
        estado integer,
        primary key (pedido_id)
    );

    create table pagamento_com_boleto (
       data_pagamento timestamp,
        data_vencimento timestamp,
        pedido_id integer not null,
        primary key (pedido_id)
    );

    create table pagamento_com_cartao (
       numero_de_parcelas integer,
        pedido_id integer not null,
        primary key (pedido_id)
    );

    create table pedido (
       id integer generated by default as identity,
        instante timestamp,
        cliente_id integer,
        endereco_de_entrega_id integer,
        primary key (id)
    );

    create table produto (
       id integer generated by default as identity,
        nome varchar(255),
        preco double,
        primary key (id)
    );

    create table produto_categaoria (
       produto_id integer not null,
        categoria_id integer not null
    );

    create table telefone (
       cliente_id integer not null,
        telefones varchar(255)
    );

    alter table cliente_pedidos 
       add constraint UK_5ghbygu6ffc8sd7dnlxud5mox unique (pedidos_id);

    alter table estado_cidades 
       add constraint UK_gijjfjo51s66b3d93dqfknv42 unique (cidades_id);

    alter table cidade 
       add constraint FKkworrwk40xj58kevvh3evi500 
       foreign key (estado_id) 
       references estado;

    alter table cliente_pedidos 
       add constraint FKprs510oqt9komm63bt9hqn6g 
       foreign key (pedidos_id) 
       references pedido;

    alter table cliente_pedidos 
       add constraint FK3fiiwebwnib50do1jwwdtp2gv 
       foreign key (cliente_id) 
       references cliente;

    alter table endereco 
       add constraint FK8b1kcb3wucapb8dejshyn5fsx 
       foreign key (cidade_id) 
       references cidade;

    alter table endereco 
       add constraint FK8s7ivtl4foyhrfam9xqom73n9 
       foreign key (cliente_id) 
       references cliente;

    alter table estado_cidades 
       add constraint FKdsru97k6bsynqe9wc4teuap59 
       foreign key (cidades_id) 
       references cidade;

    alter table estado_cidades 
       add constraint FKb2ry2y5u2495mmteeveyt6ifd 
       foreign key (estado_id) 
       references estado;

    alter table item_pedido 
       add constraint FK60ym08cfoysa17wrn1swyiuda 
       foreign key (pedido_id) 
       references pedido;

    alter table item_pedido 
       add constraint FKtk55mn6d6bvl5h0no5uagi3sf 
       foreign key (produto_id) 
       references produto;

    alter table pagamento 
       add constraint FKthad9tkw4188hb3qo1lm5ueb0 
       foreign key (pedido_id) 
       references pedido;

    alter table pagamento_com_boleto 
       add constraint FKcr74vrxf8nfph0knq2bho8doo 
       foreign key (pedido_id) 
       references pagamento;

    alter table pagamento_com_cartao 
       add constraint FKta3cdnuuxclwfh52t4qi432ow 
       foreign key (pedido_id) 
       references pagamento;

    alter table pedido 
       add constraint FK30s8j2ktpay6of18lbyqn3632 
       foreign key (cliente_id) 
       references cliente;

    alter table pedido 
       add constraint FK1fihyy2fnocpuwc74674qmfkv 
       foreign key (endereco_de_entrega_id) 
       references endereco;

    alter table produto_categaoria 
       add constraint FK8x787ynuy0pwb7rs3oxop8d5o 
       foreign key (categoria_id) 
       references categoria;

    alter table produto_categaoria 
       add constraint FKcw2rbwom5a8yry1d3wth6ev8y 
       foreign key (produto_id) 
       references produto;

    alter table telefone 
       add constraint FK8aafha0njkoyoe3kvrwsy3g8u 
       foreign key (cliente_id) 
       references cliente;

    create table categoria (
       id integer generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table cidade (
       id integer generated by default as identity,
        nome varchar(255),
        estado_id integer,
        primary key (id)
    );

    create table cliente (
       id integer generated by default as identity,
        cpf_ou_cnpj varchar(255),
        email varchar(255),
        nome varchar(255),
        tipo integer,
        primary key (id)
    );

    create table cliente_pedidos (
       cliente_id integer not null,
        pedidos_id integer not null
    );

    create table endereco (
       id integer generated by default as identity,
        bairro varchar(255),
        cep varchar(255),
        complemento varchar(255),
        logradouro varchar(255),
        numero varchar(255),
        cidade_id integer,
        cliente_id integer,
        primary key (id)
    );

    create table estado (
       id integer generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table estado_cidades (
       estado_id integer not null,
        cidades_id integer not null
    );

    create table item_pedido (
       desconto double,
        preco double,
        quantidade integer,
        pedido_id integer not null,
        produto_id integer not null,
        primary key (pedido_id, produto_id)
    );

    create table pagamento (
       pedido_id integer not null,
        estado integer,
        primary key (pedido_id)
    );

    create table pagamento_com_boleto (
       data_pagamento timestamp,
        data_vencimento timestamp,
        pedido_id integer not null,
        primary key (pedido_id)
    );

    create table pagamento_com_cartao (
       numero_de_parcelas integer,
        pedido_id integer not null,
        primary key (pedido_id)
    );

    create table pedido (
       id integer generated by default as identity,
        instante timestamp,
        cliente_id integer,
        endereco_de_entrega_id integer,
        primary key (id)
    );

    create table produto (
       id integer generated by default as identity,
        nome varchar(255),
        preco double,
        primary key (id)
    );

    create table produto_categaoria (
       produto_id integer not null,
        categoria_id integer not null
    );

    create table telefone (
       cliente_id integer not null,
        telefones varchar(255)
    );

    alter table cliente_pedidos 
       add constraint UK_5ghbygu6ffc8sd7dnlxud5mox unique (pedidos_id);

    alter table estado_cidades 
       add constraint UK_gijjfjo51s66b3d93dqfknv42 unique (cidades_id);

    alter table cidade 
       add constraint FKkworrwk40xj58kevvh3evi500 
       foreign key (estado_id) 
       references estado;

    alter table cliente_pedidos 
       add constraint FKprs510oqt9komm63bt9hqn6g 
       foreign key (pedidos_id) 
       references pedido;

    alter table cliente_pedidos 
       add constraint FK3fiiwebwnib50do1jwwdtp2gv 
       foreign key (cliente_id) 
       references cliente;

    alter table endereco 
       add constraint FK8b1kcb3wucapb8dejshyn5fsx 
       foreign key (cidade_id) 
       references cidade;

    alter table endereco 
       add constraint FK8s7ivtl4foyhrfam9xqom73n9 
       foreign key (cliente_id) 
       references cliente;

    alter table estado_cidades 
       add constraint FKdsru97k6bsynqe9wc4teuap59 
       foreign key (cidades_id) 
       references cidade;

    alter table estado_cidades 
       add constraint FKb2ry2y5u2495mmteeveyt6ifd 
       foreign key (estado_id) 
       references estado;

    alter table item_pedido 
       add constraint FK60ym08cfoysa17wrn1swyiuda 
       foreign key (pedido_id) 
       references pedido;

    alter table item_pedido 
       add constraint FKtk55mn6d6bvl5h0no5uagi3sf 
       foreign key (produto_id) 
       references produto;

    alter table pagamento 
       add constraint FKthad9tkw4188hb3qo1lm5ueb0 
       foreign key (pedido_id) 
       references pedido;

    alter table pagamento_com_boleto 
       add constraint FKcr74vrxf8nfph0knq2bho8doo 
       foreign key (pedido_id) 
       references pagamento;

    alter table pagamento_com_cartao 
       add constraint FKta3cdnuuxclwfh52t4qi432ow 
       foreign key (pedido_id) 
       references pagamento;

    alter table pedido 
       add constraint FK30s8j2ktpay6of18lbyqn3632 
       foreign key (cliente_id) 
       references cliente;

    alter table pedido 
       add constraint FK1fihyy2fnocpuwc74674qmfkv 
       foreign key (endereco_de_entrega_id) 
       references endereco;

    alter table produto_categaoria 
       add constraint FK8x787ynuy0pwb7rs3oxop8d5o 
       foreign key (categoria_id) 
       references categoria;

    alter table produto_categaoria 
       add constraint FKcw2rbwom5a8yry1d3wth6ev8y 
       foreign key (produto_id) 
       references produto;

    alter table telefone 
       add constraint FK8aafha0njkoyoe3kvrwsy3g8u 
       foreign key (cliente_id) 
       references cliente;

    create table categoria (
       id integer generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table cidade (
       id integer generated by default as identity,
        nome varchar(255),
        estado_id integer,
        primary key (id)
    );

    create table cliente (
       id integer generated by default as identity,
        cpf_ou_cnpj varchar(255),
        email varchar(255),
        nome varchar(255),
        tipo integer,
        primary key (id)
    );

    create table cliente_pedidos (
       cliente_id integer not null,
        pedidos_id integer not null
    );

    create table endereco (
       id integer generated by default as identity,
        bairro varchar(255),
        cep varchar(255),
        complemento varchar(255),
        logradouro varchar(255),
        numero varchar(255),
        cidade_id integer,
        cliente_id integer,
        primary key (id)
    );

    create table estado (
       id integer generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table estado_cidades (
       estado_id integer not null,
        cidades_id integer not null
    );

    create table item_pedido (
       desconto double,
        preco double,
        quantidade integer,
        pedido_id integer not null,
        produto_id integer not null,
        primary key (pedido_id, produto_id)
    );

    create table pagamento (
       pedido_id integer not null,
        estado integer,
        primary key (pedido_id)
    );

    create table pagamento_com_boleto (
       data_pagamento timestamp,
        data_vencimento timestamp,
        pedido_id integer not null,
        primary key (pedido_id)
    );

    create table pagamento_com_cartao (
       numero_de_parcelas integer,
        pedido_id integer not null,
        primary key (pedido_id)
    );

    create table pedido (
       id integer generated by default as identity,
        instante timestamp,
        cliente_id integer,
        endereco_de_entrega_id integer,
        primary key (id)
    );

    create table produto (
       id integer generated by default as identity,
        nome varchar(255),
        preco double,
        primary key (id)
    );

    create table produto_categaoria (
       produto_id integer not null,
        categoria_id integer not null
    );

    create table telefone (
       cliente_id integer not null,
        telefones varchar(255)
    );

    alter table cliente_pedidos 
       add constraint UK_5ghbygu6ffc8sd7dnlxud5mox unique (pedidos_id);

    alter table estado_cidades 
       add constraint UK_gijjfjo51s66b3d93dqfknv42 unique (cidades_id);

    alter table cidade 
       add constraint FKkworrwk40xj58kevvh3evi500 
       foreign key (estado_id) 
       references estado;

    alter table cliente_pedidos 
       add constraint FKprs510oqt9komm63bt9hqn6g 
       foreign key (pedidos_id) 
       references pedido;

    alter table cliente_pedidos 
       add constraint FK3fiiwebwnib50do1jwwdtp2gv 
       foreign key (cliente_id) 
       references cliente;

    alter table endereco 
       add constraint FK8b1kcb3wucapb8dejshyn5fsx 
       foreign key (cidade_id) 
       references cidade;

    alter table endereco 
       add constraint FK8s7ivtl4foyhrfam9xqom73n9 
       foreign key (cliente_id) 
       references cliente;

    alter table estado_cidades 
       add constraint FKdsru97k6bsynqe9wc4teuap59 
       foreign key (cidades_id) 
       references cidade;

    alter table estado_cidades 
       add constraint FKb2ry2y5u2495mmteeveyt6ifd 
       foreign key (estado_id) 
       references estado;

    alter table item_pedido 
       add constraint FK60ym08cfoysa17wrn1swyiuda 
       foreign key (pedido_id) 
       references pedido;

    alter table item_pedido 
       add constraint FKtk55mn6d6bvl5h0no5uagi3sf 
       foreign key (produto_id) 
       references produto;

    alter table pagamento 
       add constraint FKthad9tkw4188hb3qo1lm5ueb0 
       foreign key (pedido_id) 
       references pedido;

    alter table pagamento_com_boleto 
       add constraint FKcr74vrxf8nfph0knq2bho8doo 
       foreign key (pedido_id) 
       references pagamento;

    alter table pagamento_com_cartao 
       add constraint FKta3cdnuuxclwfh52t4qi432ow 
       foreign key (pedido_id) 
       references pagamento;

    alter table pedido 
       add constraint FK30s8j2ktpay6of18lbyqn3632 
       foreign key (cliente_id) 
       references cliente;

    alter table pedido 
       add constraint FK1fihyy2fnocpuwc74674qmfkv 
       foreign key (endereco_de_entrega_id) 
       references endereco;

    alter table produto_categaoria 
       add constraint FK8x787ynuy0pwb7rs3oxop8d5o 
       foreign key (categoria_id) 
       references categoria;

    alter table produto_categaoria 
       add constraint FKcw2rbwom5a8yry1d3wth6ev8y 
       foreign key (produto_id) 
       references produto;

    alter table telefone 
       add constraint FK8aafha0njkoyoe3kvrwsy3g8u 
       foreign key (cliente_id) 
       references cliente;

    create table categoria (
       id integer generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table cidade (
       id integer generated by default as identity,
        nome varchar(255),
        estado_id integer,
        primary key (id)
    );

    create table cliente (
       id integer generated by default as identity,
        cpf_ou_cnpj varchar(255),
        email varchar(255),
        nome varchar(255),
        tipo integer,
        primary key (id)
    );

    create table cliente_pedidos (
       cliente_id integer not null,
        pedidos_id integer not null
    );

    create table endereco (
       id integer generated by default as identity,
        bairro varchar(255),
        cep varchar(255),
        complemento varchar(255),
        logradouro varchar(255),
        numero varchar(255),
        cidade_id integer,
        cliente_id integer,
        primary key (id)
    );

    create table estado (
       id integer generated by default as identity,
        nome varchar(255),
        primary key (id)
    );

    create table estado_cidades (
       estado_id integer not null,
        cidades_id integer not null
    );

    create table item_pedido (
       desconto double,
        preco double,
        quantidade integer,
        pedido_id integer not null,
        produto_id integer not null,
        primary key (pedido_id, produto_id)
    );

    create table pagamento (
       pedido_id integer not null,
        estado integer,
        primary key (pedido_id)
    );

    create table pagamento_com_boleto (
       data_pagamento timestamp,
        data_vencimento timestamp,
        pedido_id integer not null,
        primary key (pedido_id)
    );

    create table pagamento_com_cartao (
       numero_de_parcelas integer,
        pedido_id integer not null,
        primary key (pedido_id)
    );

    create table pedido (
       id integer generated by default as identity,
        instante timestamp,
        cliente_id integer,
        endereco_de_entrega_id integer,
        primary key (id)
    );

    create table produto (
       id integer generated by default as identity,
        nome varchar(255),
        preco double,
        primary key (id)
    );

    create table produto_categaoria (
       produto_id integer not null,
        categoria_id integer not null
    );

    create table telefone (
       cliente_id integer not null,
        telefones varchar(255)
    );

    alter table cliente_pedidos 
       add constraint UK_5ghbygu6ffc8sd7dnlxud5mox unique (pedidos_id);

    alter table estado_cidades 
       add constraint UK_gijjfjo51s66b3d93dqfknv42 unique (cidades_id);

    alter table cidade 
       add constraint FKkworrwk40xj58kevvh3evi500 
       foreign key (estado_id) 
       references estado;

    alter table cliente_pedidos 
       add constraint FKprs510oqt9komm63bt9hqn6g 
       foreign key (pedidos_id) 
       references pedido;

    alter table cliente_pedidos 
       add constraint FK3fiiwebwnib50do1jwwdtp2gv 
       foreign key (cliente_id) 
       references cliente;

    alter table endereco 
       add constraint FK8b1kcb3wucapb8dejshyn5fsx 
       foreign key (cidade_id) 
       references cidade;

    alter table endereco 
       add constraint FK8s7ivtl4foyhrfam9xqom73n9 
       foreign key (cliente_id) 
       references cliente;

    alter table estado_cidades 
       add constraint FKdsru97k6bsynqe9wc4teuap59 
       foreign key (cidades_id) 
       references cidade;

    alter table estado_cidades 
       add constraint FKb2ry2y5u2495mmteeveyt6ifd 
       foreign key (estado_id) 
       references estado;

    alter table item_pedido 
       add constraint FK60ym08cfoysa17wrn1swyiuda 
       foreign key (pedido_id) 
       references pedido;

    alter table item_pedido 
       add constraint FKtk55mn6d6bvl5h0no5uagi3sf 
       foreign key (produto_id) 
       references produto;

    alter table pagamento 
       add constraint FKthad9tkw4188hb3qo1lm5ueb0 
       foreign key (pedido_id) 
       references pedido;

    alter table pagamento_com_boleto 
       add constraint FKcr74vrxf8nfph0knq2bho8doo 
       foreign key (pedido_id) 
       references pagamento;

    alter table pagamento_com_cartao 
       add constraint FKta3cdnuuxclwfh52t4qi432ow 
       foreign key (pedido_id) 
       references pagamento;

    alter table pedido 
       add constraint FK30s8j2ktpay6of18lbyqn3632 
       foreign key (cliente_id) 
       references cliente;

    alter table pedido 
       add constraint FK1fihyy2fnocpuwc74674qmfkv 
       foreign key (endereco_de_entrega_id) 
       references endereco;

    alter table produto_categaoria 
       add constraint FK8x787ynuy0pwb7rs3oxop8d5o 
       foreign key (categoria_id) 
       references categoria;

    alter table produto_categaoria 
       add constraint FKcw2rbwom5a8yry1d3wth6ev8y 
       foreign key (produto_id) 
       references produto;

    alter table telefone 
       add constraint FK8aafha0njkoyoe3kvrwsy3g8u 
       foreign key (cliente_id) 
       references cliente;
